// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsZCl90xmmK8DADjfpXoK6bkIoWoVqGCs',
    appId: '1:985581212942:android:becca1ca9ad8fe8e8af35f',
    messagingSenderId: '985581212942',
    projectId: 'real-time-messaging-9b660',
    storageBucket: 'real-time-messaging-9b660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz7DDlXfQX5PVkXlAtCiRE8DE6BmPlOL4',
    appId: '1:985581212942:ios:01394c3e12c76fcd8af35f',
    messagingSenderId: '985581212942',
    projectId: 'real-time-messaging-9b660',
    storageBucket: 'real-time-messaging-9b660.firebasestorage.app',
    iosBundleId: 'com.example.webSocketApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjojs_eP3oDsjjlYj65i_g_jxyIN3sBdw',
    appId: '1:985581212942:web:4315cd9dfc9fb94a8af35f',
    messagingSenderId: '985581212942',
    projectId: 'real-time-messaging-9b660',
    authDomain: 'real-time-messaging-9b660.firebaseapp.com',
    storageBucket: 'real-time-messaging-9b660.firebasestorage.app',
    measurementId: 'G-Q3R0GJ4YZV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz7DDlXfQX5PVkXlAtCiRE8DE6BmPlOL4',
    appId: '1:985581212942:ios:01394c3e12c76fcd8af35f',
    messagingSenderId: '985581212942',
    projectId: 'real-time-messaging-9b660',
    storageBucket: 'real-time-messaging-9b660.firebasestorage.app',
    iosBundleId: 'com.example.webSocketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjojs_eP3oDsjjlYj65i_g_jxyIN3sBdw',
    appId: '1:985581212942:web:8bf5a78b7376090b8af35f',
    messagingSenderId: '985581212942',
    projectId: 'real-time-messaging-9b660',
    authDomain: 'real-time-messaging-9b660.firebaseapp.com',
    storageBucket: 'real-time-messaging-9b660.firebasestorage.app',
    measurementId: 'G-X0QZQYZTFV',
  );
}
